### ISSUE TITLE
Problem using python-chess

### ISSUE THREAD

**Issue by djdekker** [serg-meus/k2#1] opened 2016-06-12 07:15 UTC
I'm using K2 0.83 with PicoChess using [python-chess](https://github.com/niklasf/python-chess) by @niklasf. I compiled K2 on Raspberry Pi 3 with -march=armv6 to ensure backwards compatibility with RPi2.

The problem is: when K2 leaves the opening book it stops responding. What could be the cause?

There was another engine, [Cinnamon](https://github.com/gekomad/Cinnamon) by @gekomad, which also had this error. It was related to an infinite loop when closing stdin and to the use of isready/readyok. Cinnamon has been fixed now ([pull requests #3 and #4](https://github.com/gekomad/Cinnamon/issues?q=is%3Apr+is%3Aclosed)).

Traceback (most recent call last):
  File "./picochess.py", line 841, in <module>
    main()
  File "./picochess.py", line 788, in main
    stop_search_and_clock()
  File "./picochess.py", line 205, in stop_search_and_clock
    stop_search()
  File "./picochess.py", line 198, in stop_search
    engine.stop()
  File "/opt/picochess/engine.py", line 230, in stop
    self.engine.stop()
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 1249, in stop
    return self._queue_command(command, async_callback)
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 890, in _queue_command
    return future.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 397, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.4/threading.py", line 290, in wait
    waiter.acquire()

**Comment by niklasf** [comment] 2016-06-12 10:20
With pure Python chess I can get k2 to communicate nicely with python-chess 0.14.1 on my computer:

```
import chess
import chess.uci
import sys
import logging

logging.basicConfig(level=logging.DEBUG)

e = chess.uci.popen_engine([sys.argv[1]])
e.uci()

e.position(chess.Board("rnbqkbnr/ppp2ppp/8/3pp3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq d6 0 3"))

print(e.go(movetime=2000))
```

**Comment by djdekker** [comment] 2016-06-27 17:51
Hi @serg-meus and @niklasf,

Thank you for your attention and for your time and efforts to solve this issue.

I compiled the latest version of K2, but it still shows the same behaviour when using it with PicoChess (by means of the python-chess library). In the mean time I've found the same issue with the Rodent_II engine by @nescitus. Because many other engines are not affected, I assume (for now) that PicoChess is not at fault here.

Could it perhaps have anything to do with python-chess sending 'isready' during search and then output strings getting mixed up?

Greetings,
DJ

**Comment by serg-meus** [comment] 2016-06-28 15:45
Hello, @djdekker, thank you for your interest.

Are you sure that K2 has been compiled successfully and executable file has permissions to execute? Can you connect your RPi to display, run the terminal and execute the engine in terminal? It may be done by following commands:
1)  cd path_to_k2
2) ./k2
3) go

Best regards,
Sergey Meus

**Comment by djdekker** [comment] 2016-06-28 17:11
Hi Sergey,
K2 runs on my RPi3: I made a [screencast](https://www.youtube.com/watch?v=mjVlsTHdkmE) to show you. It seems, however, that K2 stops calculating at depth 11.
Best regards,
Dirk-Jan

**Comment by serg-meus** [comment] 2016-06-28 17:36
@djdekker, everything is correct, engine seems to work fine. By default K2 use time control 5 minutes per game and the calculation stop is caused by timer.
I am going to install PicoChess on my laptop and try it, but it may take a lot of time, I am not an expert in installation of Python packages and my little children will not accelerate the process :)

Best regards,
Sergey Meus

**Comment by djdekker** [comment] 2016-06-28 18:40
`pi@raspberrypi:/opt/picochess $ sudo python3 ./picochess.py -c -e /opt/picochess/engines/armv7l/k2`

If you run picochess like this in console mode (so that you don't need the physical DGT board) with K2 selected as its engine, you will see that picochess never receives the PV or score from the engine when search has started. Just enter `a2a4` as the first move and enter `go` to start the search. There's no answer coming from the engine.

Trying exactly the same procedure with, for example, Stockfish or Gull is successful (replace `/opt/picochess/engines/armv7l/k2` with `/opt/picochess/engines/armv7l/a-stockf`).

**Comment by serg-meus** [comment] 2016-06-29 04:59
@djdekker, is it possible to get *all* commands sent from picochess to K2 from begin of session to the moment where K2 is not responding?

**Comment by djdekker** [comment] 2016-06-29 06:18
Hi Sergey, it's the python-chess library that handles the chess playing part of PicoChess. I don't know the internals of python-chess, but @niklasf does.

**Comment by serg-meus** [comment] 2016-06-29 06:27
Hi Dirk-Jan, thanks for your response.
I will try to look at python-chess sources, too.

**Comment by serg-meus** [comment] 2016-06-30 17:32
@djdekker, @niklasf, @nescitus
Gentlemen, I got it.
1. My chess engine does not support completely the UCI protocol, in particular, command 'go ... searchmoves ...' is not supported, and this is a bug. After 'searchmoves' there must be a list of moves that engine must to take into account, all the rest moves must be skipped.
2. My chess engine freezes if not supported command inside 'go' command comes, and this is a bug.
3. The picochess via python-chess sends to engine 'go ... searchmoves ...' command with list of all legal moves, I don't know why, but this is not a bug.

Bug #2 fixed by a474d64

**Comment by nescitus** [comment] 2016-06-30 17:51
thank You very much! fixing it will take a while, but since I think that
Rodent needs a root move list anyhow, this is not a problem.

2016-06-30 19:32 GMT+02:00 serg-meus <notifications@github.com>:

**Comment by djdekker** [comment] 2016-06-30 18:07
Thank you very much, Sergey! I just made a fresh K2 compile and it works fine now. :smiley:

**Comment by djdekker** [comment] 2016-06-30 19:19
Sorry Sergey, there still seems to be an issue with strings passed from the K2 engine to python-chess. In the log here below it's an invalid cp value, but sometimes it's an exception parsing the pv.

2016-06-30 20:40:45.223 ERROR        uci - _info: exception parsing score cp value
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 762, in _info
    score_cp = int(token)
ValueError: invalid literal for int() with base 10: 'readyok'
2016-06-30 20:40:45.224 DEBUG dgtdisplay - run: Search started
2016-06-30 20:40:45.229 ERROR        uci - _info: exception parsing pv
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 747, in _info
    pv.append(board.push_uci(token))
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 2795, in push_uci
    move = self.parse_uci(uci)
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 2773, in parse_uci
    move = Move.from_uci(uci)
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 776, in from_uci
    raise ValueError("expected uci string to be of length 4 or 5: {0}".format(repr(uci)))
ValueError: expected uci string to be of length 4 or 5: '!'
2016-06-30 20:40:45.230 DEBUG  picochess - main: received event from evt_queue: EVT_NEW_SCORE
2016-06-30 20:40:45.235 ERROR        uci - _info: exception parsing pv
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 747, in _info
    pv.append(board.push_uci(token))
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 2795, in push_uci
    move = self.parse_uci(uci)
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 2773, in parse_uci
    move = Move.from_uci(uci)
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 776, in from_uci
    raise ValueError("expected uci string to be of length 4 or 5: {0}".format(repr(uci)))
ValueError: expected uci string to be of length 4 or 5: '!'
2016-06-30 20:40:45.237 DEBUG  picochess - main: received event from evt_queue: EVT_NEW_PV
2016-06-30 20:40:45.237 DEBUG dgtdisplay - run: received message from msg_queue: MSG_NEW_SCORE
2016-06-30 20:40:45.250 DEBUG dgtdisplay - run: received message from msg_queue: MSG_NEW_PV
2016-06-30 20:40:45.249 ERROR        uci - _info: exception parsing pv
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 747, in _info
    pv.append(board.push_uci(token))
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 2795, in push_uci
    move = self.parse_uci(uci)
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 2773, in parse_uci
    move = Move.from_uci(uci)
  File "/usr/local/lib/python3.4/dist-packages/chess/__init__.py", line 776, in from_uci
    raise ValueError("expected uci string to be of length 4 or 5: {0}".format(repr(uci)))
ValueError: expected uci string to be of length 4 or 5: '?'

**Comment by djdekker** [comment] 2016-06-30 20:05
After 1. f3 e5 2. g4 Qh4# I'm getting this error immediately after putting the black Queen on h4:

Traceback (most recent call last):
  File "./picochess.py", line 826, in <module>
    main()
  File "./picochess.py", line 542, in main
    process_fen(event.fen)
  File "./picochess.py", line 245, in process_fen
    move = list(game.legal_moves)[legal_fens.index(fen)]
IndexError: list index out of range

**Comment by LocutusOfPenguin** [comment] 2016-07-01 11:34
@djdekker 
what version of picochess & engine you are using?

@nescitus 
not being able to use rodent_II after the book left, blocks abit my "personality" update for picochess.
I hope y can find the time to fix this. Thank you.

**Comment by serg-meus** [comment] 2016-07-01 17:03
@djdekker, I cant reproduce the mentioned errors, on my laptop picochess and K2 plays correctly, and f2f3 e7e5 g2g4 is also looks fine. 

I think it would be better if you change one line in picochess.py to make log= on interaction between engine and python-chess. Then run picochess with keys '-l debug -l logfile.log' and send me log file with erroneous K2 behavior, if any.

The original line is:
`    logging.getLogger("chess.uci").setLevel(logging.INFO)  # don't want to get so many python-chess uci messages`

The changed line is:
`    logging.getLogger("chess.uci").setLevel(logging.DEBUG)  #want to get so many python-chess uci messages`

**Comment by LocutusOfPenguin** [comment] 2016-07-01 20:09
well...today i (internally) released v0.68. This is alot more stable as the older version (solving some bug issues on our list).
But right now, its not tested enough, so i prob have to wait until beginning of next week.

**Comment by djdekker** [comment] 2016-07-02 05:22
@serg-meus Here is a log file (with python-chess log level set to DEBUG) to show you what's happening with the invalid pv / score strings:
https://dl.dropboxusercontent.com/u/10122745/20160702_picochess.log

**Comment by serg-meus** [comment] 2016-07-03 19:30
@djdekker, please try 7eed29b.
Regards,
SM

**Comment by djdekker** [comment] 2016-07-04 19:09
Hello Sergey,
Thank you for your commit! I rebuilt the K2 engine from source. The invalid pv/score strings are gone :smiley:, but now I found that K2 sometimes sends corrupt 'readyok' messages. In [one log file](https://dl.dropboxusercontent.com/u/10122745/20160704_picochess_k2.log) I saw it sending 'readyok152' instead of 'readyok'. Mysterious!
Greetings,
DJ

**Comment by LocutusOfPenguin** [comment] 2016-07-05 13:34
Perhaps same as: https://github.com/niklasf/python-chess/issues/83 ?

**Comment by serg-meus** [comment] 2016-07-05 17:09
@djdekker, @LocutusOfPenguin, thank you very much!
I never thought that it would be problem there.
I hope cee2289 will solve this, because it's hard to reproduce multi-threading errors.

**Closed** 2016-07-10 15:38 UTC
Labels: bug
